name: Markdown linting

on: push

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nosborn/github-action-markdown-cli@v1.1.1
      name: Markdownlint
